AWSTemplateFormatVersion: '2010-09-09'
Description: TelAgri Bank Dashboard - Parameter Store Setup for Environment Configuration

Parameters:
  ProjectName:
    Type: String
    Default: telagri-bank-dashboard
    Description: Project name for parameter naming

  GitHubOrg:
    Type: String
    Description: GitHub organization name
    Default: your-github-org

  GitHubRepo:
    Type: String
    Description: GitHub repository name
    Default: telagri-bank-dashboard

Resources:
  # KMS Key for encrypting sensitive parameters
  ParameterStoreKMSKey:
    Type: AWS::KMS::Key
    Properties:
      Description: KMS Key for TelAgri Bank Dashboard Parameter Store encryption
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action: kms:*
            Resource: '*'
          - Sid: Allow Parameter Store Service
            Effect: Allow
            Principal:
              Service: ssm.amazonaws.com
            Action:
              - kms:Decrypt
              - kms:DescribeKey
              - kms:Encrypt
              - kms:GenerateDataKey
              - kms:ReEncrypt*
            Resource: '*'
          - Sid: Allow GitHub Actions Role
            Effect: Allow
            Principal:
              AWS: !GetAtt GitHubActionsRole.Arn
            Action:
              - kms:Decrypt
              - kms:DescribeKey
            Resource: '*'

  # KMS Key Alias
  ParameterStoreKMSKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub alias/${ProjectName}-parameter-store
      TargetKeyId: !Ref ParameterStoreKMSKey

  # GitHub Actions IAM Role
  GitHubActionsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ProjectName}-github-actions-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Sub arn:aws:iam::${AWS::AccountId}:oidc-provider/token.actions.githubusercontent.com
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                token.actions.githubusercontent.com:aud: sts.amazonaws.com
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub repo:${GitHubOrg}/${GitHubRepo}:*
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/PowerUserAccess # For CDK deployment
      Policies:
        - PolicyName: ParameterStoreAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: AllowParameterStoreRead
                Effect: Allow
                Action:
                  - ssm:GetParameter
                  - ssm:GetParameters
                  - ssm:GetParametersByPath
                Resource:
                  - !Sub arn:aws:ssm:*:${AWS::AccountId}:parameter/telagri/monitoring/*/frontend/*
                  - !Sub arn:aws:ssm:*:${AWS::AccountId}:parameter/telagri/monitoring/*/backend/*
              - Sid: AllowParameterStoreWrite
                Effect: Allow
                Action:
                  - ssm:PutParameter
                  - ssm:DeleteParameter
                  - ssm:AddTagsToResource
                  - ssm:RemoveTagsFromResource
                Resource:
                  - !Sub arn:aws:ssm:*:${AWS::AccountId}:parameter/telagri/monitoring/*/frontend/*
                  - !Sub arn:aws:ssm:*:${AWS::AccountId}:parameter/telagri/monitoring/*/backend/*
              - Sid: AllowKMSDecryption
                Effect: Allow
                Action:
                  - kms:Decrypt
                  - kms:DescribeKey
                Resource:
                  - !Ref ParameterStoreKMSKey

  # Sample Frontend Configuration Parameters (will be overwritten by actual values)
  DevFrontendConfig:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /telagri/monitoring/dev/frontend/env
      Type: SecureString
      Value: |
        # Frontend Environment Configuration (Safe for builds)
        VITE_APP_NAME=TelAgri Monitoring
        VITE_APP_VERSION=2.0.0
        VITE_APP_ENVIRONMENT=development
        VITE_SUPABASE_URL=https://jhelkawgkjohvzsusrnw.supabase.co
        VITE_SUPABASE_ANON_KEY=your-dev-anon-key-placeholder
        VITE_APP_URL=https://dashboard-dev.telagri.com
        VITE_APP_GOOGLE_MAPS_API_KEY=your-google-maps-key
        VITE_APP_GOOGLE_AUTH_CLIENT_ID=your-google-oauth-client-id
        VITE_APP_TAG_MANAGER_KEY=G-XXXXXXX
        VITE_APP_SENTRY_DSN=https://public-key@sentry.io/project
        VITE_APP_CDN_URL=https://cdn.telagri.com/
        VITE_APP_HYPERDX_API_KEY=your-hyperdx-key
        VITE_APP_HYPERDX_ENABLED=false
      Description: Frontend environment configuration for development
      KmsKeyId: !Ref ParameterStoreKMSKey
      Tags:
        Environment: dev
        Type: frontend
        Project: !Ref ProjectName

  DevBackendConfig:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /telagri/monitoring/dev/backend/env
      Type: SecureString
      Value: |
        # Backend Environment Configuration (Server-side only)
        SENDGRID_API_KEY=SG.REPLACE_WITH_REAL_SENDGRID_API_KEY
        SENDGRID_FROM_EMAIL=noreply@telagri.com
        SITE_URL=https://dashboard-dev.telagri.com
        VITE_APP_URL=https://dashboard-dev.telagri.com
        SUPABASE_PROJECT_ID=your-project-id
        SUPABASE_DB_PASSWORD=REPLACE_WITH_REAL_DB_PASSWORD
      Description: Backend environment configuration for development
      KmsKeyId: !Ref ParameterStoreKMSKey
      Tags:
        Environment: dev
        Type: backend
        Project: !Ref ProjectName

  ProdFrontendConfig:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /telagri/monitoring/prod/frontend/env
      Type: SecureString
      Value: |
        # Frontend Environment Configuration (Safe for builds)
        VITE_APP_NAME=TelAgri Monitoring
        VITE_APP_VERSION=2.0.0
        VITE_APP_ENVIRONMENT=production
        VITE_SUPABASE_URL=https://your-prod-project.supabase.co
        VITE_SUPABASE_ANON_KEY=your-prod-anon-key-placeholder
        VITE_APP_URL=https://dashboard.telagri.com
        VITE_APP_GOOGLE_MAPS_API_KEY=your-google-maps-key
        VITE_APP_GOOGLE_AUTH_CLIENT_ID=your-google-oauth-client-id
        VITE_APP_TAG_MANAGER_KEY=G-XXXXXXX
        VITE_APP_SENTRY_DSN=https://public-key@sentry.io/project
        VITE_APP_CDN_URL=https://cdn.telagri.com/
        VITE_APP_HYPERDX_API_KEY=your-hyperdx-key
        VITE_APP_HYPERDX_ENABLED=true
      Description: Frontend environment configuration for production
      KmsKeyId: !Ref ParameterStoreKMSKey
      Tags:
        Environment: prod
        Type: frontend
        Project: !Ref ProjectName

Outputs:
  GitHubActionsRoleArn:
    Description: ARN of the GitHub Actions IAM Role
    Value: !GetAtt GitHubActionsRole.Arn
    Export:
      Name: !Sub ${ProjectName}-github-actions-role-arn

  KMSKeyId:
    Description: KMS Key ID for Parameter Store encryption
    Value: !Ref ParameterStoreKMSKey
    Export:
      Name: !Sub ${ProjectName}-parameter-store-kms-key

  KMSKeyAlias:
    Description: KMS Key Alias for Parameter Store encryption
    Value: !Ref ParameterStoreKMSKeyAlias
    Export:
      Name: !Sub ${ProjectName}-parameter-store-kms-alias

  ParameterPrefix:
    Description: Parameter Store prefix for environment configurations
    Value: !Sub /${ProjectName}
    Export:
      Name: !Sub ${ProjectName}-parameter-prefix